/* Generated by packages/contracts/scripts/gen.mjs from the backend pydantic models.
 * Do not edit by hand: run `pnpm contracts:gen`. */

/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Language".
 */
export type Language = "en" | "hi" | "ta";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "BookingStatus".
 */
export type BookingStatus = "booked" | "cancelled";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "CabMode".
 */
export type CabMode = "working" | "paused";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MachineState".
 */
export type MachineState = "ENGINE_OFF" | "IDLE" | "WORKING" | "TRAVELLING";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ProximityTier".
 */
export type ProximityTier = "clear" | "caution" | "danger" | "critical";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "RiskBand".
 */
export type RiskBand = "green" | "amber" | "red";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SensorTier".
 */
export type SensorTier = "basic" | "standard" | "advanced";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "GroundCondition".
 */
export type GroundCondition = "dry" | "wet" | "muddy" | "rocky" | "frozen";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "EventType".
 */
export type EventType =
  | "alert"
  | "alert_ack"
  | "alert_cleared"
  | "idle_segment"
  | "anomaly"
  | "incident"
  | "near_miss"
  | "equipment_problem"
  | "lesson_offered"
  | "lesson_completed"
  | "drill_result"
  | "booking"
  | "checklist"
  | "risk_band_change"
  | "connectivity"
  | "site_issue";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Priority".
 */
export type Priority = "P1" | "P2" | "P3" | "P4";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IdleReason".
 */
export type IdleReason =
  "SCHEDULED_BREAK" | "WARM_UP" | "UNATTENDED_RUNNING" | "WAITING_FOR_TRUCK" | "HABIT" | "UNKNOWN";
/**
 * Brief column `Seatbelt Status` (exact text from the sample).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SeatbeltStatus".
 */
export type SeatbeltStatus = "Fastened" | "Unfastened";
/**
 * Brief column `Safety Alert Triggered` (exact text from the sample).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "YesNo".
 */
export type YesNo = "Yes" | "No";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MachineType".
 */
export type MachineType = "excavator" | "wheel_loader" | "dozer";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ZoneType".
 */
export type ZoneType = "dig" | "loading" | "haul_road" | "stockpile" | "break_area";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LessonFormat".
 */
export type LessonFormat = "narrated_cards" | "quiz" | "drill";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "QuantityUnit".
 */
export type QuantityUnit = "loads" | "m" | "m2" | "m3";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ProximitySource".
 */
export type ProximitySource = "sensor" | "camera";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ReportType".
 */
export type ReportType = "incident" | "near_miss" | "equipment_problem";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Severity".
 */
export type Severity = "low" | "medium" | "high";
export type TaskStatus = "scheduled" | "active" | "done";
export type GroundCondition1 = "dry" | "wet" | "muddy" | "rocky" | "frozen";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TaskStatus".
 */
export type TaskStatus1 = "scheduled" | "active" | "done";

export interface ShiftMateContracts {}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "AckRequest".
 */
export interface AckRequest {
  action?: "ack" | "later" | "done";
}
/**
 * The parts of alert_policy.yaml the cab applies itself (sound and speech timing).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "AlertTimings".
 */
export interface AlertTimings {
  p1_speech_repeat_s: number;
  p2_tone_repeat_s: number;
  reduced_p1_repeat_s: number;
  p3_snooze_min: number;
  paused_idle_seconds: number;
}
/**
 * An alert as the cab draws it (payload of `alert`, `alert_queued`, `alert_feed`,
 * `alert_cleared`; the alert policy engine decides status and presentation).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "AlertView".
 */
export interface AlertView {
  alert_id: string;
  rule_id: string;
  priority: "P1" | "P2" | "P3" | "P4";
  message_key: string;
  category: string;
  raised_at: string;
  status: string;
  presentation: "takeover" | "banner" | "strip" | "feed" | "reduced";
  sound: string;
  speak: boolean;
  requires_ack: boolean;
  escalated: boolean;
  queued_count: number;
  context?: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "AlertsSnapshot".
 */
export interface AlertsSnapshot {
  current: AlertView | null;
  strip: AlertView | null;
  reduced: AlertView[];
  queue_count: number;
  queue_top_priority: ("P1" | "P2" | "P3" | "P4") | null;
  feed: AlertView[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "AskRequest".
 */
export interface AskRequest {
  question: string;
  language: Language;
  machine_id?: string | null;
  operator_id?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "AskResponse".
 */
export interface AskResponse {
  answer: string;
  citations: Citation[];
  answerable: boolean;
  mode: "online" | "offline";
  language: Language;
  notice_key?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Citation".
 */
export interface Citation {
  chunk_id: string;
  title: string;
  section: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "BeatView".
 */
export interface BeatView {
  id: string;
  at: string;
  action: string;
  caption: {
    [k: string]: string;
  } | null;
  done: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "BenchResult".
 */
export interface BenchResult {
  machines: number;
  sim_minutes: number;
  ticks: number;
  cpu_ms_per_tick_mean: number;
  cpu_ms_per_tick_p95: number;
  memory_mb_per_machine: number;
  upload_bytes_per_machine_per_hour: number;
  records_per_machine_per_hour: number;
  finished_at: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Booking".
 */
export interface Booking {
  booking_id: string;
  operator_id: string;
  slot_id: string;
  status: BookingStatus;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "BookingRequest".
 */
export interface BookingRequest {
  operator_id: string;
  slot_id: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "BookingView".
 */
export interface BookingView {
  booking_id: string;
  slot_id: string;
  dealer_centre?: string | null;
  start?: string | null;
  topic?: string | null;
  status: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "BreakWindow".
 */
export interface BreakWindow {
  start: string;
  minutes: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "CabConfig".
 */
export interface CabConfig {
  alerts: AlertTimings;
  checklist: ChecklistItemView[];
  checklist_voice: {
    [k: string]: {
      [k: string]: string[];
    };
  };
  camera: CameraSettings;
  languages: Language[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ChecklistItemView".
 */
export interface ChecklistItemView {
  id: string;
  text: {
    [k: string]: string;
  };
  illustration: string;
}
/**
 * What the cab's in-browser person detector needs (config/edge.yaml camera.detect).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "CameraSettings".
 */
export interface CameraSettings {
  fps: number;
  score_min: number;
  person_height_m: number;
  calibration_m: number;
  ema_alpha: number;
  post_hz: number;
  fov_deg: number;
  facing_deg: number;
  protocol_distances_m: number[];
  protocol_readings: number;
}
/**
 * `snapshot` on /ws/cab: the full current state, first on connect and after load/seek.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "CabSnapshot".
 */
export interface CabSnapshot {
  loaded: boolean;
  machine_id?: string | null;
  operator_id?: string | null;
  language?: Language | null;
  telemetry?: Telemetry | null;
  mode?: CabMode | null;
  alerts?: AlertsSnapshot | null;
  online?: boolean | null;
  sync?: SyncUpdate | null;
  captions?: boolean | null;
  waiting_for?: string | null;
  risk?: RiskUpdate | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Telemetry".
 */
export interface Telemetry {
  ts: string;
  machine_id: string;
  state: MachineState;
  mode: CabMode;
  engine_on: boolean;
  travel_speed_kmh: number;
  seatbelt_fastened: boolean;
  seat_occupied: boolean | null;
  proximity_m: number | null;
  proximity_bearing_deg: number | null;
  proximity_source: string | null;
  proximity_tier: ProximityTier | null;
  heat_index_c: number;
  risk_score: number;
  risk_band: RiskBand;
  task_id: string | null;
  task_progress_qty: number;
  continuous_operation_min: number;
  sensor_tier: SensorTier;
  thresholds: {
    [k: string]: number;
  };
  x_m?: number | null;
  y_m?: number | null;
  heading_deg?: number | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SyncUpdate".
 */
export interface SyncUpdate {
  online: boolean;
  outbox_size: number;
  last_sync: string | null;
  last_error?: string | null;
  synced_now?: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "RiskUpdate".
 */
export interface RiskUpdate {
  score: number;
  band: RiskBand;
  top: {
    [k: string]: unknown;
  }[];
  thresholds: {
    [k: string]: number;
  };
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "CameraProtocolReading".
 */
export interface CameraProtocolReading {
  true_m: number;
  estimate_m: number;
}
/**
 * POST /eval/camera-protocol: one session of the TRD §12 camera protocol from the cab.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "CameraProtocolRun".
 */
export interface CameraProtocolRun {
  calibrated: boolean;
  /**
   * @minItems 1
   */
  readings: [CameraProtocolReading, ...CameraProtocolReading[]];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "CameraReading".
 */
export interface CameraReading {
  machine_id: string;
  distance_m: number;
  confidence: number;
  bearing_deg?: number | null;
  ts?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Capability".
 */
export interface Capability {
  id: string;
  enabled: boolean;
  reason?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "CaptionsRequest".
 */
export interface CaptionsRequest {
  on: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ChecklistAnswer".
 */
export interface ChecklistAnswer {
  item_id: string;
  ok: boolean;
  note?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ChecklistItem".
 */
export interface ChecklistItem {
  id: string;
  text: LocalizedText;
  illustration: string;
}
/**
 * A user-facing string in all three languages (golden rule 10).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LocalizedText".
 */
export interface LocalizedText {
  en: string;
  hi: string;
  ta: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ChecklistResult".
 */
export interface ChecklistResult {
  saved: boolean;
  problems: number;
  report_ids: string[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ChecklistSubmit".
 */
export interface ChecklistSubmit {
  operator_id: string;
  machine_id: string;
  answers: ChecklistAnswer[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Climate".
 */
export interface Climate {
  month_profiles: {
    [k: string]: MonthProfile;
  };
  /**
   * @minItems 1
   */
  history_seasons: [SeasonSpan, ...SeasonSpan[]];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MonthProfile".
 */
export interface MonthProfile {
  temp_mean_c: number;
  temp_amp_c: number;
  rh_mean: number;
  rain_prob: number;
  rain_mean_mm_h?: number;
  wind_mean_kmh?: number;
  dust_event_prob?: number;
  fog_prob?: number;
}
/**
 * History days [first, last] (1-based, inclusive) use this month's climate and daylight.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SeasonSpan".
 */
export interface SeasonSpan {
  /**
   * @minItems 2
   * @maxItems 2
   */
  days: [unknown, unknown];
  month: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "CompletionView".
 */
export interface CompletionView {
  lesson_id: string;
  ts: string;
  score: number;
  duration_s: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Conditions".
 */
export interface Conditions {
  ambient_temp_c: number;
  relative_humidity_pct: number;
  heat_index_c: number;
  precipitation_mm_h: number;
  wind_kmh: number;
  visibility_m: number;
  is_night: boolean;
  ground_condition: GroundCondition;
  sunrise?: string | null;
  sunset?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Connectivity".
 */
export interface Connectivity {
  online: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "DemoState".
 */
export interface DemoState {
  scenario: string | null;
  site_id: string | null;
  focus_machine: string | null;
  sim_time: string | null;
  playing: boolean;
  speed: number;
  waiting_for: string | null;
  online: boolean;
  captions: boolean;
  beats: BeatView[];
  signed_in: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "DrillHazard".
 */
export interface DrillHazard {
  id: string;
  text: LocalizedText;
  is_hazard: boolean;
  scene: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "DrillResult".
 */
export interface DrillResult {
  operator_id: string;
  drill_id: string;
  ts: string;
  hazards: HazardResult[];
  score: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "HazardResult".
 */
export interface HazardResult {
  hazard_id: string;
  reaction_ms?: number | null;
  correct: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "DrillResultRequest".
 */
export interface DrillResultRequest {
  operator_id: string;
  drill_id: string;
  hazards: HazardAnswer[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "HazardAnswer".
 */
export interface HazardAnswer {
  hazard_id: string;
  reaction_ms?: number | null;
  correct: boolean;
}
/**
 * A drill result as facts ("5 of 7", "0.8 s"), never a single score (D-013).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "DrillView".
 */
export interface DrillView {
  drill_id: string;
  ts: string;
  correct: number;
  total: number;
  mean_reaction_ms?: number | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  code: string;
  message: string;
}
/**
 * Every API error uses this envelope: `{"error": {"code", "message"}}`.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ErrorResponse".
 */
export interface ErrorResponse {
  error: ErrorBody;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "EstimateReason".
 */
export interface EstimateReason {
  key: string;
  feature: string;
  minutes: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "EstimateUpdate".
 */
export interface EstimateUpdate {
  task_id: string | null;
  estimate: TaskEstimate | null;
  likely_finish: TaskEstimate | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TaskEstimate".
 */
export interface TaskEstimate {
  p10: number;
  p50: number;
  p90: number;
  reasons: EstimateReason[];
  low_confidence?: boolean;
  remaining?: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  event_id: string;
  ts: string;
  machine_id: string;
  operator_id?: string | null;
  site_id: string;
  type: EventType;
  priority?: Priority | null;
  code: string;
  payload?: {
    [k: string]: unknown;
  };
  shared_with_supervisor?: boolean;
  synced?: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "FleetMix".
 */
export interface FleetMix {
  excavator: number;
  wheel_loader: number;
  dozer: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "FleetOverview".
 */
export interface FleetOverview {
  sites: FleetSite[];
  machines_total: number;
  by_type: {
    [k: string]: number;
  };
  by_tier: {
    [k: string]: number;
  };
  records: {
    [k: string]: number;
  };
  scale_machines: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "FleetSite".
 */
export interface FleetSite {
  site_id: string;
  name: string;
  country: string;
  timezone: string;
  latest_date: string | null;
  machines_total: number;
  machines_active: number;
  by_type: {
    [k: string]: number;
  };
  by_tier: {
    [k: string]: number;
  };
  risk_bands: {
    [k: string]: number;
  };
  ground_condition: string | null;
  heat_index_c: number | null;
  last_ingest: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "FleetPattern".
 */
export interface FleetPattern {
  dimension: string;
  task_type: string;
  condition: string;
  multiplier: number;
  change_pct: number;
  tasks: number;
  machines: number;
  reference: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "FuelMetrics".
 */
export interface FuelMetrics {
  fuel_l: number;
  idle_fuel_l: number;
  fuel_per_load_l: number | null;
  usual_fuel_per_load_l: number | null;
  loads: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "FuelRates".
 */
export interface FuelRates {
  idle: number;
  working: number;
  travel: number;
}
/**
 * Local site coordinates in metres (site layout frame).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Gps".
 */
export interface Gps {
  x_m: number;
  y_m: number;
}
/**
 * How often a finished lesson's habits were seen: the week before this one, and this week.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "HabitTrend".
 */
export interface HabitTrend {
  lesson_id: string;
  codes: string[];
  previous_week: number;
  this_week: number;
}
/**
 * Answer of `GET /health` on the edge gateway and the fleet service.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "HealthResponse".
 */
export interface HealthResponse {
  service: "edge" | "fleet";
  status: "ok";
  version: string;
  sim_clock?: string | null;
  network_online?: boolean | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "HourMinutes".
 */
export interface HourMinutes {
  hour: number;
  minutes: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IdleCause".
 */
export interface IdleCause {
  reason: string;
  minutes: number;
  share: number;
  site_issue: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IdleCausesResponse".
 */
export interface IdleCausesResponse {
  site_id: string;
  date: string;
  machines: number;
  total_idle_min: number;
  lead: IdleCause | null;
  causes: IdleCause[];
  truck_wait_by_hour: HourMinutes[];
  suggestion: Suggestion | null;
  suggestions: Suggestion[];
}
/**
 * One plain-language suggestion; the console turns `key` + values into text.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Suggestion".
 */
export interface Suggestion {
  key: string;
  reason: string;
  minutes: number;
  zone_id?: string | null;
  window_start?: string | null;
  window_end?: string | null;
  save_min_low?: number | null;
  save_min_high?: number | null;
  basis_days?: number | null;
  lesson_id?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IdleSegmentPayload".
 */
export interface IdleSegmentPayload {
  start: string;
  end: string;
  duration_s: number;
  reason: IdleReason;
  confidence: number;
  evidence: string[];
  fuel_l: number;
  response_taken: string;
  provisional?: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IdleSegmentView".
 */
export interface IdleSegmentView {
  start: string;
  end: string;
  minutes: number;
  reason: IdleReason;
  confidence: number;
  evidence: string[];
  fuel_l: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IdleThresholds".
 */
export interface IdleThresholds {
  segment_min_seconds: number;
  habit_threshold_minutes: number;
  unattended_seat_empty_seconds: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IngestRequest".
 */
export interface IngestRequest {
  /**
   * Sending machine or process (e.g. EXC001).
   */
  source?: string | null;
  records: {
    [k: string]: unknown;
  }[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IngestResponse".
 */
export interface IngestResponse {
  kind: "intervals" | "events" | "reports" | "tasks";
  received: number;
  inserted: number;
  updated?: number;
  duplicates: number;
  rejected?: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "InsightNote".
 */
export interface InsightNote {
  key: string;
  values?: {
    [k: string]: unknown;
  };
  lesson_id?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "InsightsResponse".
 */
export interface InsightsResponse {
  operator_id: string;
  range: "shift" | "week";
  totals_min: {
    [k: string]: number;
  };
  time_split: TimeSplitSegment[];
  idle_segments: IdleSegmentView[];
  fuel: FuelMetrics;
  anomalies: {
    [k: string]: unknown;
  }[];
  coaching: InsightNote[];
  positives: InsightNote[];
  days?: {
    [k: string]: unknown;
  }[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TimeSplitSegment".
 */
export interface TimeSplitSegment {
  kind: string;
  start: string;
  end: string;
  minutes: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IntentRequest".
 */
export interface IntentRequest {
  utterance: string;
  language: Language;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IntentResponse".
 */
export interface IntentResponse {
  intent: string;
  slots?: {
    [k: string]: unknown;
  };
  matched?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IntervalRecord".
 */
export interface IntervalRecord {
  timestamp: string;
  machine_id: string;
  operator_id: string;
  engine_hours: number;
  fuel_used_l: number;
  load_cycles: number;
  idling_time_min: number;
  seatbelt_status: SeatbeltStatus;
  safety_alert_triggered: YesNo;
  record_id?: string | null;
  interval_start?: string | null;
  interval_minutes?: number | null;
  site_id?: string | null;
  machine_type?: MachineType | null;
  sensor_tier?: SensorTier | null;
  task_id?: string | null;
  task_type?: string | null;
  engine_on_min?: number | null;
  working_min?: number | null;
  travel_min?: number | null;
  seat_occupied_min?: number | null;
  seatbelt_unfastened_working_s?: number | null;
  avg_engine_rpm?: number | null;
  max_travel_speed_kmh?: number | null;
  truck_present_min?: number | null;
  truck_wait_min?: number | null;
  min_proximity_m?: number | null;
  proximity_caution_count?: number | null;
  proximity_danger_count?: number | null;
  proximity_critical_count?: number | null;
  ambient_temp_c?: number | null;
  relative_humidity_pct?: number | null;
  heat_index_c?: number | null;
  precipitation_mm?: number | null;
  wind_kmh?: number | null;
  visibility_m?: number | null;
  is_night?: boolean | null;
  ground_condition?: GroundCondition | null;
  continuous_operation_min?: number | null;
  coolant_temp_c?: number | null;
  incident_count?: number | null;
  near_miss_count?: number | null;
  idle_warmup_min?: number | null;
  idle_break_min?: number | null;
  idle_truck_wait_min?: number | null;
  idle_unattended_min?: number | null;
  idle_habit_min?: number | null;
  idle_unknown_min?: number | null;
  fuel_per_load_cycle_l?: number | null;
  task_progress_qty?: number | null;
  risk_score_max?: number | null;
  p1_alert_count?: number | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Layout".
 */
export interface Layout {
  size: Size;
  zones: Zone[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Size".
 */
export interface Size {
  w: number;
  h: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Zone".
 */
export interface Zone {
  id: string;
  type: ZoneType;
  polygon?: [unknown, unknown][] | null;
  polyline?: [unknown, unknown][] | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Lesson".
 */
export interface Lesson {
  id: string;
  title: LocalizedText;
  format: LessonFormat;
  duration_s: number;
  triggers: string[];
  cards?: LessonCard[];
  quiz?: QuizQuestion[];
  hazards?: DrillHazard[];
  art?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LessonCard".
 */
export interface LessonCard {
  text: LocalizedText;
  illustration: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "QuizQuestion".
 */
export interface QuizQuestion {
  q: LocalizedText;
  /**
   * @minItems 2
   * @maxItems 4
   */
  options:
    | [LocalizedText, LocalizedText]
    | [LocalizedText, LocalizedText, LocalizedText]
    | [LocalizedText, LocalizedText, LocalizedText, LocalizedText];
  answer: number;
  explain: LocalizedText;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LessonCompleteRequest".
 */
export interface LessonCompleteRequest {
  operator_id: string;
  score: number;
  duration_s: number;
  language: Language;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LessonCompletion".
 */
export interface LessonCompletion {
  operator_id: string;
  lesson_id: string;
  ts: string;
  score: number;
  duration_s: number;
  language: Language;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LessonOffer".
 */
export interface LessonOffer {
  lesson_id: string;
  because: string[];
  reason: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LessonSummary".
 */
export interface LessonSummary {
  id: string;
  title: {
    [k: string]: string;
  };
  format: string;
  duration_s: number;
  triggers: string[];
  completed?: boolean;
  art?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LiveIngest".
 */
export interface LiveIngest {
  records_last_60s: number;
  records_per_s: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Machine".
 */
export interface Machine {
  machine_id: string;
  machine_type: MachineType;
  model: string;
  model_year: number;
  sensor_tier: SensorTier;
  site_id: string;
  engine_hours_start: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MachineDaySummary".
 */
export interface MachineDaySummary {
  machine_id: string;
  machine_type: string | null;
  model: string | null;
  sensor_tier: string | null;
  operator_id: string | null;
  operator_name: string | null;
  tasks: TaskProgressView[];
  engine_on_min: number;
  working_min: number;
  idle_min: number;
  last_seen: string | null;
  track: "done" | "on_track" | "behind" | "not_started" | "unknown";
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TaskProgressView".
 */
export interface TaskProgressView {
  task_id: string;
  task_type: string;
  zone_id: string | null;
  planned_quantity: number | null;
  done_quantity: number;
  unit: string | null;
  status: string;
  progress_pct: number | null;
  expected_min: number | null;
  elapsed_min: number | null;
  track: "done" | "on_track" | "behind" | "not_started" | "unknown";
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MachineInfo".
 */
export interface MachineInfo {
  machine: Machine;
  focus: boolean;
  capabilities: Capability[];
  features: {
    [k: string]: boolean;
  };
  low_confidence: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MachineProfile".
 */
export interface MachineProfile {
  machine_type: MachineType;
  display_name: LocalizedText;
  id_prefix: string;
  /**
   * @minItems 1
   */
  example_models: [string, ...string[]];
  load_cycle_definition: string;
  passes_per_load: MinMax;
  seconds_per_pass: MeanSd;
  fuel_lph: FuelRates;
  rpm: RpmLevels;
  max_travel_speed_kmh: number;
  warm_up: WarmUp;
  idle: IdleThresholds;
  proximity_m: ProximityDistances;
  unsafe: UnsafeThresholds;
  /**
   * @minItems 1
   */
  task_types: [string, ...string[]];
  tasks: {
    [k: string]: TaskProfile;
  };
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MinMax".
 */
export interface MinMax {
  min: number;
  max: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MeanSd".
 */
export interface MeanSd {
  mean: number;
  sd: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "RpmLevels".
 */
export interface RpmLevels {
  idle: number;
  working: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "WarmUp".
 */
export interface WarmUp {
  coolant_ready_c: number;
  max_minutes_normal: number;
  max_minutes_below_0c: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ProximityDistances".
 */
export interface ProximityDistances {
  caution: number;
  danger: number;
  critical: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "UnsafeThresholds".
 */
export interface UnsafeThresholds {
  speed_near_person_kmh: number;
  continuous_operation_warn_min: number;
  continuous_operation_limit_min: number;
}
/**
 * How a task type behaves for this machine type (used by the simulator and estimation).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TaskProfile".
 */
export interface TaskProfile {
  quantity_unit: QuantityUnit;
  base_rate_per_h: number;
  truck_dependent?: boolean;
  typical_quantity: MinMax;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MachineRisk".
 */
export interface MachineRisk {
  machine_id: string;
  band: string | null;
  score: number | null;
  amber_min: number;
  red_min: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ModeUpdate".
 */
export interface ModeUpdate {
  mode: CabMode;
  state: MachineState;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ModelRef".
 */
export interface ModelRef {
  version: string;
  files: string[];
  manifest: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "NetworkRequest".
 */
export interface NetworkRequest {
  online: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Operator".
 */
export interface Operator {
  operator_id: string;
  name: string;
  preferred_language: Language;
  experience_years: number;
  home_site_id: string;
  certifications: MachineType[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "OperatorProfile".
 */
export interface OperatorProfile {
  operator: Operator;
  language: Language;
  skill_index: {
    [k: string]: number;
  };
  lessons_completed: number;
  drills_done: number;
  recent_lessons: string[];
}
/**
 * Linear projection to the whole connected fleet. A projection, not a measurement.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Projection".
 */
export interface Projection {
  label?: "projection";
  machines: number;
  basis: string;
  hours_per_day: number;
  uplink_bytes_per_day: number;
  uplink_gb_per_day: number;
  records_per_day: number;
  records_per_s: number;
  ingest_nodes_at_measured_rate: number | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Recommendation".
 */
export interface Recommendation {
  lesson: LessonSummary;
  score: number;
  because: string[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ReportContextModel".
 */
export interface ReportContextModel {
  ts: string;
  machine_id: string;
  operator_id: string | null;
  site_id: string;
  zone_id: string | null;
  task_id: string | null;
  weather: {
    [k: string]: unknown;
  };
  risk_score: number | null;
  language: Language;
}
/**
 * Structured incident / near-miss report (TRD §6.10).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ReportDraft".
 */
export interface ReportDraft {
  type: ReportType;
  severity: Severity;
  summary_en: string;
  summary_local: string;
  people_involved: boolean;
  injury: boolean;
  /**
   * online | offline
   */
  parser: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ReportParseRequest".
 */
export interface ReportParseRequest {
  transcript: string;
  language: Language;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ReportParseResponse".
 */
export interface ReportParseResponse {
  draft: ReportDraft;
  context: ReportContextModel;
  mode: "online" | "offline";
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ReportSaveRequest".
 */
export interface ReportSaveRequest {
  draft: ReportDraft;
  context?: ReportContextModel | null;
  transcript?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ReportView".
 */
export interface ReportView {
  report_id: string;
  ts: string;
  type: string;
  severity: string | null;
  summary_en: string | null;
  machine_id: string;
  operator_id: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SafetyEventView".
 */
export interface SafetyEventView {
  event_id: string;
  ts: string;
  type: string;
  priority: string | null;
  code: string | null;
  machine_id: string;
  operator_id: string | null;
  operator_name: string | null;
  detail?: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SafetyResponse".
 */
export interface SafetyResponse {
  site_id: string;
  date: string;
  p1: SafetyEventView[];
  p2: SafetyEventView[];
  p2_counts: {
    [k: string]: number;
  };
  incidents: SafetyEventView[];
  near_misses: SafetyEventView[];
  unattended: SafetyEventView[];
  site_issues: SafetyEventView[];
  reports: ReportView[];
  risk: MachineRisk[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SavedReport".
 */
export interface SavedReport {
  report_id: string;
  ts: string;
  draft: ReportDraft;
  context: ReportContextModel;
  synced: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ScaleRun".
 */
export interface ScaleRun {
  machines: number;
  sim_minutes: number;
  records: number;
  intervals: number;
  events: number;
  requests: number;
  seconds: number;
  records_per_s: number;
  request_ms_p50: number;
  request_ms_p95: number;
  bytes_sent: number;
  bytes_per_machine_per_hour: number;
  records_per_machine_per_hour: number;
  finished_at: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ScaleStats".
 */
export interface ScaleStats {
  totals: {
    [k: string]: number;
  };
  scale_machines: number;
  live: LiveIngest;
  run: ScaleRun | null;
  bench: BenchResult | null;
  projection: Projection | null;
}
/**
 * GET /demo/scenarios: what the demo page can load.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ScenarioInfo".
 */
export interface ScenarioInfo {
  name: string;
  title: {
    [k: string]: string;
  };
  site_id: string;
  focus_machine: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ScenarioLoadRequest".
 */
export interface ScenarioLoadRequest {
  name: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SeekRequest".
 */
export interface SeekRequest {
  beat_id: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SessionResponse".
 */
export interface SessionResponse {
  profile: OperatorProfile;
  machine: MachineInfo;
  shift: ShiftResponse;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ShiftResponse".
 */
export interface ShiftResponse {
  date: string;
  operator_id: string;
  machine_id: string;
  conditions: Conditions;
  tasks: ShiftTask[];
  likely_finish: TaskEstimate | null;
  breaks: SuggestedBreak[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ShiftTask".
 */
export interface ShiftTask {
  task: Task;
  estimate: TaskEstimate | null;
  progress_qty?: number;
  zone_decal: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Task".
 */
export interface Task {
  task_id: string;
  site_id: string;
  machine_id: string;
  operator_id: string;
  task_type: string;
  zone_id: string;
  planned_quantity: number;
  quantity_unit: QuantityUnit;
  scheduled_start: string;
  actual_start?: string | null;
  actual_end?: string | null;
  actual_duration_min?: number | null;
  status?: TaskStatus;
  conditions_at_start?: TaskConditions | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TaskConditions".
 */
export interface TaskConditions {
  ground_condition: GroundCondition;
  heat_index_c: number;
  precipitation_mm_h: number;
  is_night: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SuggestedBreak".
 */
export interface SuggestedBreak {
  at: string;
  minutes: number;
  reason_key: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Shift".
 */
export interface Shift {
  start: string;
  end: string;
  breaks: BreakWindow[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ShortageWindow".
 */
export interface ShortageWindow {
  day: number;
  start: string;
  minutes: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SignInRequest".
 */
export interface SignInRequest {
  operator_id: string;
  machine_id: string;
  pin?: string | null;
  badge?: string | null;
  language: Language;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SignalTick".
 */
export interface SignalTick {
  ts: string;
  machine_id: string;
  operator_id?: string | null;
  engine_on: boolean;
  engine_hours: number;
  fuel_rate_lph: number;
  hydraulic_active: boolean;
  travel_speed_kmh: number;
  seatbelt_fastened: boolean;
  gps: Gps;
  heading_deg: number;
  load_cycles_total?: number;
  seat_occupied?: boolean | null;
  engine_rpm?: number | null;
  coolant_temp_c?: number | null;
  proximity_m?: number | null;
  proximity_bearing_deg?: number | null;
  proximity_source?: ProximitySource | null;
  truck_in_loading_zone?: boolean | null;
  ambient_temp_c: number;
  relative_humidity_pct: number;
  heat_index_c: number;
  precipitation_mm_h: number;
  wind_kmh: number;
  visibility_m: number;
  is_night: boolean;
  ground_condition: GroundCondition;
  task_id?: string | null;
  task_progress_qty?: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Site".
 */
export interface Site {
  site_id: string;
  name: string;
  country: string;
  timezone: string;
  latitude: number;
  locale_default: Language;
  /**
   * @minItems 1
   */
  languages: [Language, ...Language[]];
  units: "metric";
  climate: Climate;
  shift: Shift;
  layout: Layout;
  trucks: Trucks;
  workers: Workers;
  fleet: FleetMix;
  operators: number;
  ground_baseline?: GroundCondition1;
  training_centre: string;
  /**
   * @minItems 1
   */
  operator_names: [string, ...string[]];
  safety_overrides?: {
    [k: string]: number;
  };
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Trucks".
 */
export interface Trucks {
  count: number;
  dispatch_mean_interval_min: number;
  shortage_windows?: ShortageWindow[];
  random_shortages_per_week?: MinMax1;
  random_shortage_minutes?: MinMax2;
  shortage_interval_multiplier?: number;
}
export interface MinMax1 {
  min: number;
  max: number;
}
export interface MinMax2 {
  min: number;
  max: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Workers".
 */
export interface Workers {
  count: number;
  swing_entry_prob_per_h?: number;
}
/**
 * `entities` on /ws/site: everything on the map (5 Hz).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SiteEntities".
 */
export interface SiteEntities {
  ts: string;
  site_id: string;
  machines: {
    [k: string]: unknown;
  }[];
  trucks: {
    [k: string]: unknown;
  }[];
  workers: {
    [k: string]: unknown;
  }[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SiteInfo".
 */
export interface SiteInfo {
  site_id: string;
  name: string;
  country: string;
  timezone: string;
  machines: number;
  first_date: string | null;
  last_date: string | null;
}
/**
 * GET /site/layout: the loaded site's plan for the console map (metres, local x/y).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SiteLayout".
 */
export interface SiteLayout {
  site_id: string;
  name: string;
  timezone: string;
  focus_machine: string;
  layout: Layout;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SiteSummary".
 */
export interface SiteSummary {
  site_id: string;
  date: string;
  timezone: string;
  machines: MachineDaySummary[];
  tasks_total: number;
  tasks_done: number;
  tasks_behind: number;
  tasks_on_track: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SpeedRequest".
 */
export interface SpeedRequest {
  x: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SyncStatus".
 */
export interface SyncStatus {
  online: boolean;
  outbox_size: number;
  last_sync: string | null;
  last_error?: string | null;
  estimation_model?: string | null;
  estimation_source?: string | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TaskProgress".
 */
export interface TaskProgress {
  task_id: string;
  status: TaskStatus1;
  done_qty: number;
  planned_qty: number;
  unit: string;
}
/**
 * GET /training/progress (PRD F-LRN-06): private to the signed-in operator.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TrainingProgress".
 */
export interface TrainingProgress {
  operator_id: string;
  lessons_done: number;
  lessons_total: number;
  streak_days: number;
  completed: CompletionView[];
  drills: DrillView[];
  bookings: BookingView[];
  habits: HabitTrend[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TrainingSlot".
 */
export interface TrainingSlot {
  slot_id: string;
  dealer_centre: string;
  site_id: string;
  start: string;
  topic: string;
  seats_left: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TrendDay".
 */
export interface TrendDay {
  day: string;
  operators: number;
  suppressed: boolean;
  idle_min_by_reason?: {
    [k: string]: number;
  } | null;
  truck_wait_min?: number | null;
  p1?: number | null;
  p2?: number | null;
  near_misses?: number | null;
  incidents?: number | null;
  fuel_per_load_cycle_l?: number | null;
  seatbelt_unfastened_s_per_h?: number | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TrendGroup".
 */
export interface TrendGroup {
  group: string;
  operators: number;
  suppressed: boolean;
  habit_idle_min_per_h?: number | null;
  seatbelt_unfastened_s_per_h?: number | null;
  fuel_per_load_cycle_l?: number | null;
  p1_per_100h?: number | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TrendsResponse".
 */
export interface TrendsResponse {
  site_id: string;
  days: number;
  min_group_size: number;
  daily: TrendDay[];
  by_experience: TrendGroup[];
}
/**
 * Every WebSocket message (TRD §9): `seq` increases by one per channel.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "WsEnvelope".
 */
export interface WsEnvelope {
  type: string;
  seq: number;
  ts: string | null;
  machine_id: string | null;
  site_id: string | null;
  payload: {
    [k: string]: unknown;
  };
}
