/* Generated by packages/contracts/scripts/gen.mjs from the backend pydantic models.
 * Do not edit by hand: run `pnpm contracts:gen`. */

/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "BookingStatus".
 */
export type BookingStatus = "booked" | "cancelled";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "EventType".
 */
export type EventType =
  | "alert"
  | "alert_ack"
  | "alert_cleared"
  | "idle_segment"
  | "anomaly"
  | "incident"
  | "near_miss"
  | "lesson_offered"
  | "lesson_completed"
  | "drill_result"
  | "booking"
  | "checklist"
  | "risk_band_change"
  | "connectivity";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Priority".
 */
export type Priority = "P1" | "P2" | "P3" | "P4";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "GroundCondition".
 */
export type GroundCondition = "dry" | "wet" | "muddy" | "rocky" | "frozen";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IdleReason".
 */
export type IdleReason =
  "SCHEDULED_BREAK" | "WARM_UP" | "UNATTENDED_RUNNING" | "WAITING_FOR_TRUCK" | "HABIT" | "UNKNOWN";
/**
 * Brief column `Seatbelt Status` (exact text from the sample).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SeatbeltStatus".
 */
export type SeatbeltStatus = "Fastened" | "Unfastened";
/**
 * Brief column `Safety Alert Triggered` (exact text from the sample).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "YesNo".
 */
export type YesNo = "Yes" | "No";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MachineType".
 */
export type MachineType = "excavator" | "wheel_loader" | "dozer";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SensorTier".
 */
export type SensorTier = "basic" | "standard" | "advanced";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Language".
 */
export type Language = "en" | "hi" | "ta";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ZoneType".
 */
export type ZoneType = "dig" | "loading" | "haul_road" | "stockpile" | "break_area";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LessonFormat".
 */
export type LessonFormat = "narrated_cards" | "quiz" | "drill";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "QuantityUnit".
 */
export type QuantityUnit = "loads" | "m" | "m2" | "m3";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ProximitySource".
 */
export type ProximitySource = "sensor" | "camera";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ReportType".
 */
export type ReportType = "incident" | "near_miss" | "equipment_problem";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Severity".
 */
export type Severity = "low" | "medium" | "high";
export type GroundCondition1 = "dry" | "wet" | "muddy" | "rocky" | "frozen";
export type TaskStatus = "scheduled" | "active" | "done";
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TaskStatus".
 */
export type TaskStatus1 = "scheduled" | "active" | "done";

export interface ShiftMateContracts {}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Booking".
 */
export interface Booking {
  booking_id: string;
  operator_id: string;
  slot_id: string;
  status: BookingStatus;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "BreakWindow".
 */
export interface BreakWindow {
  start: string;
  minutes: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ChecklistItem".
 */
export interface ChecklistItem {
  id: string;
  text: LocalizedText;
  illustration: string;
}
/**
 * A user-facing string in all three languages (golden rule 10).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LocalizedText".
 */
export interface LocalizedText {
  en: string;
  hi: string;
  ta: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Climate".
 */
export interface Climate {
  month_profiles: {
    [k: string]: MonthProfile;
  };
  /**
   * @minItems 1
   */
  history_seasons: [SeasonSpan, ...SeasonSpan[]];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MonthProfile".
 */
export interface MonthProfile {
  temp_mean_c: number;
  temp_amp_c: number;
  rh_mean: number;
  rain_prob: number;
  rain_mean_mm_h?: number;
  wind_mean_kmh?: number;
  dust_event_prob?: number;
  fog_prob?: number;
}
/**
 * History days [first, last] (1-based, inclusive) use this month's climate and daylight.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SeasonSpan".
 */
export interface SeasonSpan {
  /**
   * @minItems 2
   * @maxItems 2
   */
  days: [unknown, unknown];
  month: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "DrillHazard".
 */
export interface DrillHazard {
  id: string;
  text: LocalizedText;
  is_hazard: boolean;
  scene: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "DrillResult".
 */
export interface DrillResult {
  operator_id: string;
  drill_id: string;
  ts: string;
  hazards: HazardResult[];
  score: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "HazardResult".
 */
export interface HazardResult {
  hazard_id: string;
  reaction_ms?: number | null;
  correct: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  code: string;
  message: string;
}
/**
 * Every API error uses this envelope: `{"error": {"code", "message"}}`.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ErrorResponse".
 */
export interface ErrorResponse {
  error: ErrorBody;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  event_id: string;
  ts: string;
  machine_id: string;
  operator_id?: string | null;
  site_id: string;
  type: EventType;
  priority?: Priority | null;
  code: string;
  payload?: {
    [k: string]: unknown;
  };
  shared_with_supervisor?: boolean;
  synced?: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "FleetMix".
 */
export interface FleetMix {
  excavator: number;
  wheel_loader: number;
  dozer: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "FuelRates".
 */
export interface FuelRates {
  idle: number;
  working: number;
  travel: number;
}
/**
 * Local site coordinates in metres (site layout frame).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Gps".
 */
export interface Gps {
  x_m: number;
  y_m: number;
}
/**
 * Answer of `GET /health` on the edge gateway and the fleet service.
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "HealthResponse".
 */
export interface HealthResponse {
  service: "edge" | "fleet";
  status: "ok";
  version: string;
  sim_clock?: string | null;
  network_online?: boolean | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IdleSegmentPayload".
 */
export interface IdleSegmentPayload {
  start: string;
  end: string;
  duration_s: number;
  reason: IdleReason;
  confidence: number;
  evidence: string[];
  fuel_l: number;
  response_taken: string;
  provisional?: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IdleThresholds".
 */
export interface IdleThresholds {
  segment_min_seconds: number;
  habit_threshold_minutes: number;
  unattended_seat_empty_seconds: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "IntervalRecord".
 */
export interface IntervalRecord {
  timestamp: string;
  machine_id: string;
  operator_id: string;
  engine_hours: number;
  fuel_used_l: number;
  load_cycles: number;
  idling_time_min: number;
  seatbelt_status: SeatbeltStatus;
  safety_alert_triggered: YesNo;
  record_id?: string | null;
  interval_start?: string | null;
  interval_minutes?: number | null;
  site_id?: string | null;
  machine_type?: MachineType | null;
  sensor_tier?: SensorTier | null;
  task_id?: string | null;
  task_type?: string | null;
  engine_on_min?: number | null;
  working_min?: number | null;
  travel_min?: number | null;
  seat_occupied_min?: number | null;
  seatbelt_unfastened_working_s?: number | null;
  avg_engine_rpm?: number | null;
  max_travel_speed_kmh?: number | null;
  truck_present_min?: number | null;
  truck_wait_min?: number | null;
  min_proximity_m?: number | null;
  proximity_caution_count?: number | null;
  proximity_danger_count?: number | null;
  proximity_critical_count?: number | null;
  ambient_temp_c?: number | null;
  relative_humidity_pct?: number | null;
  heat_index_c?: number | null;
  precipitation_mm?: number | null;
  wind_kmh?: number | null;
  visibility_m?: number | null;
  is_night?: boolean | null;
  ground_condition?: GroundCondition | null;
  continuous_operation_min?: number | null;
  coolant_temp_c?: number | null;
  incident_count?: number | null;
  near_miss_count?: number | null;
  idle_warmup_min?: number | null;
  idle_break_min?: number | null;
  idle_truck_wait_min?: number | null;
  idle_unattended_min?: number | null;
  idle_habit_min?: number | null;
  idle_unknown_min?: number | null;
  fuel_per_load_cycle_l?: number | null;
  task_progress_qty?: number | null;
  risk_score_max?: number | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Layout".
 */
export interface Layout {
  size: Size;
  zones: Zone[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Size".
 */
export interface Size {
  w: number;
  h: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Zone".
 */
export interface Zone {
  id: string;
  type: ZoneType;
  polygon?: [unknown, unknown][] | null;
  polyline?: [unknown, unknown][] | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Lesson".
 */
export interface Lesson {
  id: string;
  format: LessonFormat;
  duration_s: number;
  triggers: string[];
  cards?: LessonCard[];
  quiz?: QuizQuestion[];
  hazards?: DrillHazard[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LessonCard".
 */
export interface LessonCard {
  text: LocalizedText;
  illustration: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "QuizQuestion".
 */
export interface QuizQuestion {
  q: LocalizedText;
  /**
   * @minItems 2
   * @maxItems 4
   */
  options:
    | [LocalizedText, LocalizedText]
    | [LocalizedText, LocalizedText, LocalizedText]
    | [LocalizedText, LocalizedText, LocalizedText, LocalizedText];
  answer: number;
  explain: LocalizedText;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "LessonCompletion".
 */
export interface LessonCompletion {
  operator_id: string;
  lesson_id: string;
  ts: string;
  score: number;
  duration_s: number;
  language: Language;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Machine".
 */
export interface Machine {
  machine_id: string;
  machine_type: MachineType;
  model: string;
  model_year: number;
  sensor_tier: SensorTier;
  site_id: string;
  engine_hours_start: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MachineProfile".
 */
export interface MachineProfile {
  machine_type: MachineType;
  display_name: LocalizedText;
  id_prefix: string;
  /**
   * @minItems 1
   */
  example_models: [string, ...string[]];
  load_cycle_definition: string;
  passes_per_load: MinMax;
  seconds_per_pass: MeanSd;
  fuel_lph: FuelRates;
  rpm: RpmLevels;
  max_travel_speed_kmh: number;
  warm_up: WarmUp;
  idle: IdleThresholds;
  proximity_m: ProximityDistances;
  unsafe: UnsafeThresholds;
  /**
   * @minItems 1
   */
  task_types: [string, ...string[]];
  tasks: {
    [k: string]: TaskProfile;
  };
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MinMax".
 */
export interface MinMax {
  min: number;
  max: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "MeanSd".
 */
export interface MeanSd {
  mean: number;
  sd: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "RpmLevels".
 */
export interface RpmLevels {
  idle: number;
  working: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "WarmUp".
 */
export interface WarmUp {
  coolant_ready_c: number;
  max_minutes_normal: number;
  max_minutes_below_0c: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ProximityDistances".
 */
export interface ProximityDistances {
  caution: number;
  danger: number;
  critical: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "UnsafeThresholds".
 */
export interface UnsafeThresholds {
  speed_near_person_kmh: number;
  continuous_operation_warn_min: number;
  continuous_operation_limit_min: number;
}
/**
 * How a task type behaves for this machine type (used by the simulator and estimation).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TaskProfile".
 */
export interface TaskProfile {
  quantity_unit: QuantityUnit;
  base_rate_per_h: number;
  truck_dependent?: boolean;
  typical_quantity: MinMax;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Operator".
 */
export interface Operator {
  operator_id: string;
  name: string;
  preferred_language: Language;
  experience_years: number;
  home_site_id: string;
  certifications: MachineType[];
}
/**
 * Structured incident / near-miss report (TRD §6.10).
 *
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ReportDraft".
 */
export interface ReportDraft {
  type: ReportType;
  severity: Severity;
  summary_en: string;
  summary_local: string;
  people_involved: boolean;
  injury: boolean;
  /**
   * online | offline
   */
  parser: string;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Shift".
 */
export interface Shift {
  start: string;
  end: string;
  breaks: BreakWindow[];
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "ShortageWindow".
 */
export interface ShortageWindow {
  day: number;
  start: string;
  minutes: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "SignalTick".
 */
export interface SignalTick {
  ts: string;
  machine_id: string;
  operator_id?: string | null;
  engine_on: boolean;
  engine_hours: number;
  fuel_rate_lph: number;
  hydraulic_active: boolean;
  travel_speed_kmh: number;
  seatbelt_fastened: boolean;
  gps: Gps;
  heading_deg: number;
  seat_occupied?: boolean | null;
  engine_rpm?: number | null;
  coolant_temp_c?: number | null;
  proximity_m?: number | null;
  proximity_bearing_deg?: number | null;
  proximity_source?: ProximitySource | null;
  truck_in_loading_zone?: boolean | null;
  ambient_temp_c: number;
  relative_humidity_pct: number;
  heat_index_c: number;
  precipitation_mm_h: number;
  wind_kmh: number;
  visibility_m: number;
  is_night: boolean;
  ground_condition: GroundCondition;
  task_id?: string | null;
  task_progress_qty?: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Site".
 */
export interface Site {
  site_id: string;
  name: string;
  country: string;
  timezone: string;
  latitude: number;
  locale_default: Language;
  /**
   * @minItems 1
   */
  languages: [Language, ...Language[]];
  units: "metric";
  climate: Climate;
  shift: Shift;
  layout: Layout;
  trucks: Trucks;
  workers: Workers;
  fleet: FleetMix;
  operators: number;
  ground_baseline?: GroundCondition1;
  training_centre: string;
  /**
   * @minItems 1
   */
  operator_names: [string, ...string[]];
  safety_overrides?: {
    [k: string]: number;
  };
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Trucks".
 */
export interface Trucks {
  count: number;
  dispatch_mean_interval_min: number;
  shortage_windows?: ShortageWindow[];
  random_shortages_per_week?: MinMax1;
  random_shortage_minutes?: MinMax2;
  shortage_interval_multiplier?: number;
}
export interface MinMax1 {
  min: number;
  max: number;
}
export interface MinMax2 {
  min: number;
  max: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Workers".
 */
export interface Workers {
  count: number;
  swing_entry_prob_per_h?: number;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "Task".
 */
export interface Task {
  task_id: string;
  site_id: string;
  machine_id: string;
  operator_id: string;
  task_type: string;
  zone_id: string;
  planned_quantity: number;
  quantity_unit: QuantityUnit;
  scheduled_start: string;
  actual_start?: string | null;
  actual_end?: string | null;
  actual_duration_min?: number | null;
  status?: TaskStatus;
  conditions_at_start?: TaskConditions | null;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TaskConditions".
 */
export interface TaskConditions {
  ground_condition: GroundCondition;
  heat_index_c: number;
  precipitation_mm_h: number;
  is_night: boolean;
}
/**
 * This interface was referenced by `ShiftMateContracts`'s JSON-Schema
 * via the `definition` "TrainingSlot".
 */
export interface TrainingSlot {
  slot_id: string;
  dealer_centre: string;
  site_id: string;
  start: string;
  topic: string;
  seats_left: number;
}
