/**
 * Generate TypeScript types from the backend's combined JSON Schema.
 *
 *   node scripts/gen.mjs          write src/generated.ts
 *   node scripts/gen.mjs --check  fail if src/generated.ts is out of date (pnpm contracts:check)
 *
 * The schema file is produced by `shiftmate schema export` (see backend/src/shiftmate/schema).
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const root = new URL("..", import.meta.url);
const schemaPath = fileURLToPath(new URL("schema/contracts.schema.json", root));
const outPath = fileURLToPath(new URL("src/generated.ts", root));
const check = process.argv.includes("--check");

const schema = JSON.parse(await readFile(schemaPath, "utf-8"));
const banner =
  "/* Generated by packages/contracts/scripts/gen.mjs from the backend pydantic models.\n" +
  " * Do not edit by hand: run `pnpm contracts:gen`. */";

let ts = await compile(schema, "ShiftMateContracts", {
  bannerComment: banner,
  unreachableDefinitions: true, // emit every $defs entry, not only ones reachable from the root
  additionalProperties: false,
  format: true,
  style: { singleQuote: false, printWidth: 100 },
});
ts = ts.replace(/\r\n/g, "\n");

if (check) {
  let current = "";
  try {
    current = (await readFile(outPath, "utf-8")).replace(/\r\n/g, "\n");
  } catch {
    // missing file counts as out of date
  }
  if (current !== ts) {
    console.error("Contracts are out of date. Run `pnpm contracts:gen` and commit the result.");
    process.exit(1);
  }
  console.log("Contracts are up to date.");
} else {
  await writeFile(outPath, ts, "utf-8");
  console.log(`Wrote ${outPath}`);
}
