/**
 * Write docs/TRANSLATIONS_REVIEW.md: every Hindi and Tamil string next to its English source,
 * with its review state (`pnpm i18n:review`).
 *
 * Review state lives in docs/translations-reviewed.json:
 *   { "hi": { "<key>": "<the exact text that was approved>" }, "ta": { ... } }
 * A string counts as reviewed only while its current text equals the approved text, so any later
 * edit puts it back on the review list automatically.
 *
 * Sources: frontend/packages/i18n/src/locales/*.json. Lesson and checklist text from config/*.yaml
 * is added in milestone 2.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const localeDir = `${root}frontend/packages/i18n/src/locales/`;
const statusPath = `${root}docs/translations-reviewed.json`;
const outPath = `${root}docs/TRANSLATIONS_REVIEW.md`;

function flatten(tree, prefix = "", out = new Map()) {
  for (const [key, value] of Object.entries(tree)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "string") out.set(path, value);
    else flatten(value, path, out);
  }
  return out;
}

const load = (lang) => flatten(JSON.parse(readFileSync(`${localeDir}${lang}.json`, "utf-8")));
const en = load("en");
const locales = { hi: load("hi"), ta: load("ta") };
const reviewed = existsSync(statusPath)
  ? JSON.parse(readFileSync(statusPath, "utf-8"))
  : { hi: {}, ta: {} };

const cell = (s) => (s ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");
const lines = [
  "# Translations review",
  "",
  "Generated by `pnpm i18n:review`. Do not edit this file by hand.",
  "",
  "To approve a string, add it to `docs/translations-reviewed.json` under `hi` or `ta` with the",
  "exact approved text, then run `pnpm i18n:review` again. If the text changes later, it returns",
  "to the review list.",
  "",
];

for (const [lang, name] of [["hi", "Hindi (हिन्दी)"], ["ta", "Tamil (தமிழ்)"]]) {
  const rows = [...en.keys()].map((key) => {
    const text = locales[lang].get(key);
    const ok = text !== undefined && reviewed[lang]?.[key] === text;
    return { key, text, ok };
  });
  const done = rows.filter((r) => r.ok).length;
  lines.push(`## ${name}: ${done} of ${rows.length} reviewed`, "");
  lines.push("| Reviewed | Key | English | " + name + " |", "|---|---|---|---|");
  for (const r of rows) {
    lines.push(`| ${r.ok ? "yes" : "**no**"} | \`${r.key}\` | ${cell(en.get(r.key))} | ${cell(r.text)} |`);
  }
  lines.push("");
}

writeFileSync(outPath, lines.join("\n"), "utf-8");
console.log(`Wrote ${outPath}`);
