/**
 * Write docs/TRANSLATIONS_REVIEW.md: every Hindi and Tamil string next to its English source,
 * with its review state (`pnpm i18n:review`).
 *
 * Sources:
 *   - UI strings:     frontend/packages/i18n/src/locales/{en,hi,ta}.json   (key = JSON path)
 *   - Config strings: every {en, hi, ta} object in config/**\/*.yaml      (key = file:path)
 *
 * Review state lives in docs/translations-reviewed.json:
 *   { "hi": { "<key>": "<the exact text that was approved>" }, "ta": { ... } }
 * A string counts as reviewed only while its current text equals the approved text, so any later
 * edit puts it back on the review list automatically.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const root = fileURLToPath(new URL("..", import.meta.url));
const localeDir = `${root}frontend/packages/i18n/src/locales/`;
const configDir = `${root}config/`;
const statusPath = `${root}docs/translations-reviewed.json`;
const outPath = `${root}docs/TRANSLATIONS_REVIEW.md`;

/** key → { en, hi, ta } */
const entries = new Map();

// --- UI strings --------------------------------------------------------------------------------
function flatten(tree, prefix = "", out = new Map()) {
  for (const [key, value] of Object.entries(tree)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "string") out.set(path, value);
    else flatten(value, path, out);
  }
  return out;
}
const locale = (lang) => flatten(JSON.parse(readFileSync(`${localeDir}${lang}.json`, "utf-8")));
const ui = { en: locale("en"), hi: locale("hi"), ta: locale("ta") };
for (const [key, en] of ui.en) {
  entries.set(`ui:${key}`, { en, hi: ui.hi.get(key), ta: ui.ta.get(key) });
}

// --- config strings ----------------------------------------------------------------------------
function yamlFiles(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = `${dir}${name}`;
    if (statSync(path).isDirectory()) return yamlFiles(`${path}/`);
    return name.endsWith(".yaml") ? [path] : [];
  });
}
function collectLocalized(node, path, file) {
  if (Array.isArray(node)) {
    // Use an item's id (when it has one) so keys stay stable if items are reordered.
    node.forEach((item, i) => collectLocalized(item, `${path}[${item?.id ?? i}]`, file));
  } else if (node && typeof node === "object") {
    if (typeof node.en === "string" && typeof node.hi === "string" && typeof node.ta === "string") {
      entries.set(`${file}:${path}`, { en: node.en, hi: node.hi, ta: node.ta });
      return;
    }
    for (const [key, value] of Object.entries(node)) {
      collectLocalized(value, path ? `${path}.${key}` : key, file);
    }
  }
}
for (const file of yamlFiles(configDir)) {
  const name = file.slice(configDir.length);
  collectLocalized(parse(readFileSync(file, "utf-8")), "", name);
}

// --- report ------------------------------------------------------------------------------------
const reviewed = existsSync(statusPath)
  ? JSON.parse(readFileSync(statusPath, "utf-8"))
  : { hi: {}, ta: {} };
const cell = (s) => (s ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");
const lines = [
  "# Translations review",
  "",
  "Generated by `pnpm i18n:review`. Do not edit this file by hand.",
  "",
  "Keys starting with `ui:` are app strings (`frontend/packages/i18n/src/locales`); the others are",
  "`<config file>:<path>` for lesson, checklist and profile text in `config/`.",
  "",
  "To approve a string, add it to `docs/translations-reviewed.json` under `hi` or `ta` with the",
  "exact approved text, then run `pnpm i18n:review` again. If the text changes later, it returns",
  "to the review list.",
  "",
];
for (const [lang, name] of [["hi", "Hindi (हिन्दी)"], ["ta", "Tamil (தமிழ்)"]]) {
  const rows = [...entries].map(([key, text]) => ({
    key,
    en: text.en,
    text: text[lang],
    ok: text[lang] !== undefined && reviewed[lang]?.[key] === text[lang],
  }));
  const done = rows.filter((r) => r.ok).length;
  lines.push(`## ${name}: ${done} of ${rows.length} reviewed`, "");
  lines.push(`| Reviewed | Key | English | ${name} |`, "|---|---|---|---|");
  for (const r of rows) {
    lines.push(`| ${r.ok ? "yes" : "**no**"} | \`${r.key}\` | ${cell(r.en)} | ${cell(r.text)} |`);
  }
  lines.push("");
}
writeFileSync(outPath, lines.join("\n"), "utf-8");
console.log(`Wrote ${outPath} (${entries.size} strings per language)`);
